package com.zbank.enums;

public enum ErrorCode {
	INVALID_USER,
	INVALID_SESSION,
	WRONG_PASSWORD,
	NO_ACCOUNT_FOUND,
	INVALID_PATTERN,
	WRONG_USER_ID,
	WRONG_ACCOUNT_NUMBER,
	INVALID_CUSTOMER,
	INVALID_EMPLOYEE,
	INVALID_BRANCH,
	INVALID_API_KEY;
}
